/*
 * 3. Dada uma string de caracteres formada por uma sequência de letras e
 * dígitos, construa uma função que retorne uma fila na qual as letras são
 * mantidas na sequência original e os dígitos são colocados na ordem inversa.
 * Exemplos:
 * A1E5T7W8G → AETWG8751
 * 3C9H4Q6 → CHQ6493
 * Como mostram os exemplos, as letras devem ser mostradas primeiro,
 * seguidas dos dígitos.
 * Sugestão: usar na função uma fila e uma pilha;
 */
package br.com.rogerio.app;

import javax.swing.JOptionPane;
import br.com.rogerio.model.Fila_Caracteres;
import br.com.rogerio.model.Pilha_Caracteres;

/**
 *
 * @author roger
 */
public class ViewFilaCaracteres extends javax.swing.JFrame {

    Fila_Caracteres fila;
    Fila_Caracteres filaAux;
    Pilha_Caracteres pilha;

    /**
     * Creates new form ViewFilaCaracteres
     */
    public ViewFilaCaracteres() {
        initComponents();
    }

    public Fila_Caracteres func(String texto) {
        Fila_Caracteres fila = new Fila_Caracteres(20);
        Pilha_Caracteres pilha = new Pilha_Caracteres(20);
        int temp;
        for (int i = 0; i < texto.length(); i++) {
            temp = texto.charAt(i);
            if (texto.charAt(i) >= '0' && texto.charAt(i) <= '9') {
                pilha.push(temp);
            } else {
                fila.enqueue(temp);
            }
        }

        while (!pilha.isEmpty()) {
            fila.enqueue(pilha.consultar());
            pilha.pop();
        }
        return fila;
    }

    public static String mostrarFila(Fila_Caracteres fila) {
        String aux = "";
        while (!fila.isEmpty()) {
            aux += (char) fila.peek();
            fila.dequeue();
        }
        return aux;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFilaExercicio03 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCaracteres = new javax.swing.JTextField();
        jButtonExecutarComandosDaFila = new javax.swing.JButton();
        jTextFieldResultadoDaFila = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Projeto Fila Exercicio 03 Caracteres");
        setResizable(false);

        jLabel1.setText("Digite uma String de caracteres:");

        jTextFieldCaracteres.setText("A1E5T7W8G");

        jButtonExecutarComandosDaFila.setText("Executar");
        jButtonExecutarComandosDaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarComandosDaFilaActionPerformed(evt);
            }
        });

        jTextFieldResultadoDaFila.setEditable(false);

        javax.swing.GroupLayout jPanelFilaExercicio03Layout = new javax.swing.GroupLayout(jPanelFilaExercicio03);
        jPanelFilaExercicio03.setLayout(jPanelFilaExercicio03Layout);
        jPanelFilaExercicio03Layout.setHorizontalGroup(
            jPanelFilaExercicio03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilaExercicio03Layout.createSequentialGroup()
                .addGroup(jPanelFilaExercicio03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilaExercicio03Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextFieldResultadoDaFila, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilaExercicio03Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFilaExercicio03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilaExercicio03Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(94, 94, 94)))))
                .addContainerGap())
            .addGroup(jPanelFilaExercicio03Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jButtonExecutarComandosDaFila)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFilaExercicio03Layout.setVerticalGroup(
            jPanelFilaExercicio03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilaExercicio03Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButtonExecutarComandosDaFila)
                .addGap(32, 32, 32)
                .addComponent(jTextFieldResultadoDaFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFilaExercicio03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFilaExercicio03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExecutarComandosDaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarComandosDaFilaActionPerformed
        // TODO add your handling code here:
        try {
            fila = func(jTextFieldCaracteres.getText());
            jTextFieldResultadoDaFila.setText(mostrarFila(fila));

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonExecutarComandosDaFilaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFilaCaracteres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFilaCaracteres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFilaCaracteres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFilaCaracteres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFilaCaracteres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExecutarComandosDaFila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFilaExercicio03;
    private javax.swing.JTextField jTextFieldCaracteres;
    private javax.swing.JTextField jTextFieldResultadoDaFila;
    // End of variables declaration//GEN-END:variables
}
